package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Configuration options
type Config struct {
	StorageType       string
	BasePath          string
	ReportOutputPath  string
	DefaultFormat     string
	EnableMonitoring  bool
	MetricsRetention  string
	QualityThreshold  float64
	EmailNotification bool
	EmailAddress      string
}

func main() {
	fmt.Println("Welcome to the Nessi Setup Wizard!")
	fmt.Println("This wizard will help you configure Nessi for your environment.")
	fmt.Println("Press Ctrl+C at any time to exit.")
	fmt.Println()

	// Check if non-interactive mode is requested
	nonInteractive := false
	for _, arg := range os.Args {
		if arg == "--non-interactive" {
			nonInteractive = true
			break
		}
	}

	config := Config{
		StorageType:       "local",
		BasePath:          "./delta-tables",
		ReportOutputPath:  "./reports",
		DefaultFormat:     "html",
		EnableMonitoring:  true,
		MetricsRetention:  "30d",
		QualityThreshold:  0.95,
		EmailNotification: false,
		EmailAddress:      "",
	}

	if !nonInteractive {
		reader := bufio.NewReader(os.Stdin)

		// Storage configuration
		fmt.Println("=== Storage Configuration ===")
		config.StorageType = promptString(reader, "Storage type (local, s3, azure, gcp)", config.StorageType)
		config.BasePath = promptString(reader, "Base path for Delta tables", config.BasePath)
		fmt.Println()

		// Reporting configuration
		fmt.Println("=== Reporting Configuration ===")
		config.ReportOutputPath = promptString(reader, "Report output path", config.ReportOutputPath)
		config.DefaultFormat = promptString(reader, "Default report format (html, pdf, json, csv, text)", config.DefaultFormat)
		fmt.Println()

		// Monitoring configuration
		fmt.Println("=== Monitoring Configuration ===")
		config.EnableMonitoring = promptBool(reader, "Enable monitoring", config.EnableMonitoring)
		if config.EnableMonitoring {
			config.MetricsRetention = promptString(reader, "Metrics retention period (e.g., 30d, 6m, 1y)", config.MetricsRetention)
		}
		fmt.Println()

		// Quality configuration
		fmt.Println("=== Quality Configuration ===")
		config.QualityThreshold = promptFloat(reader, "Default quality threshold (0.0-1.0)", config.QualityThreshold)
		fmt.Println()

		// Notification configuration
		fmt.Println("=== Notification Configuration ===")
		config.EmailNotification = promptBool(reader, "Enable email notifications", config.EmailNotification)
		if config.EmailNotification {
			config.EmailAddress = promptString(reader, "Email address for notifications", config.EmailAddress)
		}
		fmt.Println()
	}

	// Create configuration directory
	homeDir, err := os.UserHomeDir()
	if err != nil {
		fmt.Printf("Error getting home directory: %v\n", err)
		os.Exit(1)
	}

	configDir := filepath.Join(homeDir, ".nessi")
	err = os.MkdirAll(configDir, 0755)
	if err != nil {
		fmt.Printf("Error creating config directory: %v\n", err)
		os.Exit(1)
	}

	// Create configuration file
	configPath := filepath.Join(configDir, "config.yaml")
	file, err := os.Create(configPath)
	if err != nil {
		fmt.Printf("Error creating config file: %v\n", err)
		os.Exit(1)
	}
	defer file.Close()

	// Write configuration
	fmt.Fprintln(file, "# Nessi Configuration")
	fmt.Fprintln(file, "# Generated by setup wizard")
	fmt.Fprintln(file, "")
	fmt.Fprintln(file, "storage:")
	fmt.Fprintf(file, "  type: %s\n", config.StorageType)
	fmt.Fprintf(file, "  base_path: %s\n", config.BasePath)
	fmt.Fprintln(file, "")
	fmt.Fprintln(file, "reporting:")
	fmt.Fprintf(file, "  output_path: %s\n", config.ReportOutputPath)
	fmt.Fprintf(file, "  default_format: %s\n", config.DefaultFormat)
	fmt.Fprintln(file, "")
	fmt.Fprintln(file, "monitoring:")
	fmt.Fprintf(file, "  enabled: %t\n", config.EnableMonitoring)
	if config.EnableMonitoring {
		fmt.Fprintf(file, "  metrics_retention: %s\n", config.MetricsRetention)
	}
	fmt.Fprintln(file, "")
	fmt.Fprintln(file, "quality:")
	fmt.Fprintf(file, "  threshold: %.2f\n", config.QualityThreshold)
	fmt.Fprintln(file, "")
	fmt.Fprintln(file, "notification:")
	fmt.Fprintf(file, "  email_enabled: %t\n", config.EmailNotification)
	if config.EmailNotification {
		fmt.Fprintf(file, "  email_address: %s\n", config.EmailAddress)
	}

	fmt.Printf("Configuration saved to %s\n", configPath)
	fmt.Println()
	fmt.Println("Setup complete! You can now use Nessi with your configuration.")
	fmt.Println("Run 'nessi --help' to see available commands.")
}

// promptString prompts the user for a string value
func promptString(reader *bufio.Reader, prompt, defaultValue string) string {
	fmt.Printf("%s [%s]: ", prompt, defaultValue)
	input, err := reader.ReadString('\n')
	if err != nil {
		fmt.Printf("Error reading input: %v\n", err)
		return defaultValue
	}
	
	input = strings.TrimSpace(input)
	if input == "" {
		return defaultValue
	}
	return input
}

// promptBool prompts the user for a boolean value
func promptBool(reader *bufio.Reader, prompt string, defaultValue bool) bool {
	defaultStr := "y"
	if !defaultValue {
		defaultStr = "n"
	}
	
	fmt.Printf("%s (y/n) [%s]: ", prompt, defaultStr)
	input, err := reader.ReadString('\n')
	if err != nil {
		fmt.Printf("Error reading input: %v\n", err)
		return defaultValue
	}
	
	input = strings.TrimSpace(strings.ToLower(input))
	if input == "" {
		return defaultValue
	}
	return input == "y" || input == "yes"
}

// promptFloat prompts the user for a float value
func promptFloat(reader *bufio.Reader, prompt string, defaultValue float64) float64 {
	fmt.Printf("%s [%.2f]: ", prompt, defaultValue)
	input, err := reader.ReadString('\n')
	if err != nil {
		fmt.Printf("Error reading input: %v\n", err)
		return defaultValue
	}
	
	input = strings.TrimSpace(input)
	if input == "" {
		return defaultValue
	}
	
	value, err := fmt.Sscanf(input, "%f", &defaultValue)
	if err != nil || value == 0 {
		fmt.Printf("Invalid input, using default: %.2f\n", defaultValue)
		return defaultValue
	}
	return defaultValue
}
