// Code generated by MockGen. DO NOT EDIT.
// Source: glue.go

// Package aws is a generated GoMock package.
package aws

import (
	context "context"
	reflect "reflect"

	glue "github.com/aws/aws-sdk-go-v2/service/glue"
	gomock "github.com/golang/mock/gomock"
	types "github.com/nessi-dev/nessi/pkg/api/types"
)

// MockGlueAPI is a mock of GlueAPI interface.
type MockGlueAPI struct {
	ctrl     *gomock.Controller
	recorder *MockGlueAPIMockRecorder
}

// MockGlueAPIMockRecorder is the mock recorder for MockGlueAPI.
type MockGlueAPIMockRecorder struct {
	mock *MockGlueAPI
}

// NewMockGlueAPI creates a new mock instance.
func NewMockGlueAPI(ctrl *gomock.Controller) *MockGlueAPI {
	mock := &MockGlueAPI{ctrl: ctrl}
	mock.recorder = &MockGlueAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGlueAPI) EXPECT() *MockGlueAPIMockRecorder {
	return m.recorder
}

// GetDatabases mocks base method.
func (m *MockGlueAPI) GetDatabases(ctx context.Context, params *glue.GetDatabasesInput, optFns ...func(*glue.Options)) (*glue.GetDatabasesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetDatabases", varargs...)
	ret0, _ := ret[0].(*glue.GetDatabasesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatabases indicates an expected call of GetDatabases.
func (mr *MockGlueAPIMockRecorder) GetDatabases(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabases", reflect.TypeOf((*MockGlueAPI)(nil).GetDatabases), varargs...)
}

// GetTable mocks base method.
func (m *MockGlueAPI) GetTable(ctx context.Context, params *glue.GetTableInput, optFns ...func(*glue.Options)) (*glue.GetTableOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTable", varargs...)
	ret0, _ := ret[0].(*glue.GetTableOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTable indicates an expected call of GetTable.
func (mr *MockGlueAPIMockRecorder) GetTable(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTable", reflect.TypeOf((*MockGlueAPI)(nil).GetTable), varargs...)
}

// GetTableDetails mocks base method.
func (m *MockGlueAPI) GetTableDetails(ctx context.Context, database, table string) (*types.TableDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableDetails", ctx, database, table)
	ret0, _ := ret[0].(*types.TableDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableDetails indicates an expected call of GetTableDetails.
func (mr *MockGlueAPIMockRecorder) GetTableDetails(ctx, database, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableDetails", reflect.TypeOf((*MockGlueAPI)(nil).GetTableDetails), ctx, database, table)
}

// GetTables mocks base method.
func (m *MockGlueAPI) GetTables(ctx context.Context, params *glue.GetTablesInput, optFns ...func(*glue.Options)) (*glue.GetTablesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTables", varargs...)
	ret0, _ := ret[0].(*glue.GetTablesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTables indicates an expected call of GetTables.
func (mr *MockGlueAPIMockRecorder) GetTables(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTables", reflect.TypeOf((*MockGlueAPI)(nil).GetTables), varargs...)
}

// UpdateTable mocks base method.
func (m *MockGlueAPI) UpdateTable(ctx context.Context, params *glue.UpdateTableInput, optFns ...func(*glue.Options)) (*glue.UpdateTableOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateTable", varargs...)
	ret0, _ := ret[0].(*glue.UpdateTableOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTable indicates an expected call of UpdateTable.
func (mr *MockGlueAPIMockRecorder) UpdateTable(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTable", reflect.TypeOf((*MockGlueAPI)(nil).UpdateTable), varargs...)
}
