package cli

import (
	"context"
	"encoding/json"
	"fmt"
	"os"

	"github.com/apache/arrow/go/v15/arrow"
	"github.com/apache/arrow/go/v15/arrow/ipc"
	"github.com/nessi-dev/nessi/pkg/datalake"
	"github.com/nessi-dev/nessi/pkg/quality/engine"
	"github.com/nessi-dev/nessi/pkg/report"
	"github.com/nessi-dev/nessi/pkg/security"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

// Default HTML template for quality reports
const defaultHTMLTemplate = `<!DOCTYPE html>
<html>
<head>
    <title>Nessi Quality Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            color: #333;
        }
        .header {
            background-color: #2c3e50;
            color: white;
            padding: 20px;
            margin-bottom: 20px;
        }
        .section {
            margin-bottom: 30px;
            border: 1px solid #ddd;
            padding: 15px;
            border-radius: 5px;
        }
        h1, h2, h3 {
            color: #2c3e50;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        .metric-good {
            color: green;
        }
        .metric-warning {
            color: orange;
        }
        .metric-critical {
            color: red;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 0.8em;
            color: #777;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Nessi Quality Report</h1>
        <p>Generated on: {{.timestamp}}</p>
    </div>

    <div class="section">
        <h2>Table Information</h2>
        <p><strong>Table Path:</strong> {{.table_path}}</p>
    </div>

    <div class="section">
        <h2>Data Quality Metrics</h2>
        <table>
            <tr>
                <th>Metric</th>
                <th>Value</th>
                <th>Status</th>
            </tr>
            {{range .data.metrics}}
            <tr>
                <td>{{.name}}</td>
                <td>{{.value}}</td>
                <td class="metric-{{.status}}">{{.status}}</td>
            </tr>
            {{end}}
        </table>
    </div>

    <div class="section">
        <h2>Column Statistics</h2>
        <table>
            <tr>
                <th>Column</th>
                <th>Type</th>
                <th>Min</th>
                <th>Max</th>
                <th>Avg</th>
                <th>Null %</th>
            </tr>
            {{range .data.columns}}
            <tr>
                <td>{{.name}}</td>
                <td>{{.type}}</td>
                <td>{{.min}}</td>
                <td>{{.max}}</td>
                <td>{{.avg}}</td>
                <td>{{.null_percent}}%</td>
            </tr>
            {{end}}
        </table>
    </div>

    <div class="footer">
        <p>Generated by Nessi CLI v0.10.3 | 2023-2025 Nessi Project</p>
    </div>
</body>
</html>`

// CLI represents the command-line interface
var CLI struct {
	RootCmd      *cobra.Command
	Config       *viper.Viper
	Engine       engine.QualityEngine
	Security     *security.SecurityManager
	Datalake     *datalake.Reader
	ConfigPath   string
	Token        string
	TablePath    string
	OutputFormat string
}

// Init initializes the CLI
func Init() {
	// Register error handlers for common error types
	RegisterErrorHandlers()

	// Initialize error suggestions
	common.InitDefaultSuggestions()

	// Initialize CLI components
	CLI.Config = viper.New()
	CLI.RootCmd = &cobra.Command{
		Use:   "nessi",
		Short: "Nessi - Delta Lake Data Quality Tool",
		Long: `Nessi is a powerful tool for managing data quality in Delta Lake tables.
It provides features for validation, profiling, monitoring, and reporting.`,
		Version: "v0.10.3", // Update as needed
	}

	// Add error handling flags to the root command
	AddErrorHandlingFlags(CLI.RootCmd)

	// Add info command
	infoCmd := &cobra.Command{
		Use:   "info",
		Short: "Show Nessi CLI and feature info",
		Long:  "Display information about the Nessi CLI, enabled features, and upgrade options.",
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Printf("Nessi CLI %s\n", CLI.RootCmd.Version)
			fmt.Println("Delta Lake support: enabled")
			fmt.Println("Python extensions: enabled")
			fmt.Println("Telemetry: disabled")
			fmt.Println("Error handling: enhanced")
			fmt.Println("Team features: not available (OSS Edition)")
			fmt.Println()
			fmt.Println("Want RCA dashboards, team alerts, or governance features?")
			fmt.Println("   Learn about LakeDiff: https://lakediff.com")
		},
	}

	// Add the info command to the root command
	CLI.RootCmd.AddCommand(infoCmd)

	// Add global flags
	CLI.RootCmd.PersistentFlags().StringVar(&CLI.ConfigPath, "config", "", "Path to configuration file")
	CLI.RootCmd.PersistentFlags().StringVar(&CLI.Token, "token", "", "Authentication token")
	CLI.RootCmd.PersistentFlags().StringVar(&CLI.OutputFormat, "output", "json", "Output format (json|yaml|text)")

	// Initialize subcommands
	initValidateCmd()
	initProfileCmd()
	initMonitorCmd()
	initReportCmd()
	initUserCmd()
	initSchemaTreeCmd()
	initTestErrorCmd()
}

// Execute runs the CLI
func Execute() error {
	// Wrap all commands with error handling
	WrapAllCommands(CLI.RootCmd)

	// Execute the command
	return CLI.RootCmd.Execute()
}

func init() {
	// Initialize CLI
	CLI.RootCmd = &cobra.Command{
		Use:   "nessi",
		Short: "Nessi - Delta Lake Data Quality Tool",
		Long: `Nessi is a powerful tool for managing data quality in Delta Lake tables.
It provides features for validation, profiling, monitoring, and reporting.`,
		Version: "v0.10.3", // Update as needed
	}

	// Add global flags
	CLI.RootCmd.PersistentFlags().StringVar(&CLI.ConfigPath, "config", "", "Path to configuration file")
	CLI.RootCmd.PersistentFlags().StringVar(&CLI.Token, "token", "", "Authentication token")
	CLI.RootCmd.PersistentFlags().StringVar(&CLI.OutputFormat, "output", "json", "Output format (json|yaml|text)")
}

// initValidateCmd initializes the validate command
func initValidateCmd() {
	validateCmd := &cobra.Command{
		Use:   "validate [table_path]",
		Short: "Validate data quality rules",
		Long:  "Validate data quality rules for a Delta Lake table.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			CLI.TablePath = args[0]
			fmt.Printf("Validating table: %s\n", CLI.TablePath)

			// TODO: Implement validation logic

			return nil
		},
	}

	validateCmd.Flags().StringVar(&CLI.ConfigPath, "rules", "", "Path to rules file")
	CLI.RootCmd.AddCommand(validateCmd)
}

// initProfileCmd initializes the profile command
func initProfileCmd() {
	profileCmd := &cobra.Command{
		Use:   "profile [table_path]",
		Short: "Generate data profile",
		Long:  "Generate a data profile for a Delta Lake table.",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 {
				CLI.TablePath = args[0]
			}

			if CLI.TablePath == "" {
				return fmt.Errorf("table path is required")
			}

			fmt.Printf("Generating profile for table: %s\n", CLI.TablePath)

			// Check if the file exists
			if _, err := os.Stat(CLI.TablePath); os.IsNotExist(err) {
				return fmt.Errorf("path '%s' does not exist", CLI.TablePath)
			}

			// TODO: Implement profile generation logic

			return nil
		},
	}

	profileCmd.Flags().StringVar(&CLI.TablePath, "table", "", "Path to Delta Lake table")
	profileCmd.Flags().StringVar(&CLI.OutputFormat, "format", "html", "Output format (html, json, csv)")
	CLI.RootCmd.AddCommand(profileCmd)
}

// initMonitorCmd initializes the monitor command
func initMonitorCmd() {
	monitorCmd := &cobra.Command{
		Use:   "monitor [table_path]",
		Short: "Monitor table metrics",
		Long:  "Monitor metrics for a Delta Lake table over time.",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 {
				CLI.TablePath = args[0]
			}

			if CLI.TablePath == "" {
				return fmt.Errorf("table path is required")
			}

			fmt.Printf("Monitoring table: %s\n", CLI.TablePath)

			// TODO: Implement monitoring logic

			return nil
		},
	}

	monitorCmd.Flags().StringVar(&CLI.TablePath, "table", "", "Path to Delta Lake table")
	monitorCmd.Flags().StringVar(&CLI.OutputFormat, "format", "html", "Output format (html, json, csv)")
	CLI.RootCmd.AddCommand(monitorCmd)
}

// initReportCmd initializes the report command
func initReportCmd() {
	reportCmd := &cobra.Command{
		Use:   "report",
		Short: "Generate reports",
		Long:  "Generate various reports for Delta Lake tables.",
		RunE: func(cmd *cobra.Command, args []string) error {
			if CLI.TablePath == "" {
				return fmt.Errorf("table path is required")
			}

			// Parse report format
			reportFormatStr := cmd.Flag("format").Value.String()
			var reportFormat report.ReportFormat
			switch reportFormatStr {
			case "html":
				reportFormat = report.HTML
			case "pdf":
				reportFormat = report.PDF
			case "json":
				reportFormat = report.JSON
			case "csv":
				reportFormat = report.CSV
			default:
				return fmt.Errorf("unsupported report format: %s", reportFormatStr)
			}

			// Get output path
			outputPath := cmd.Flag("output").Value.String()

			// Create report generator
			reportGenerator, err := report.NewReportGenerator("templates", outputPath)
			if err != nil {
				return fmt.Errorf("failed to create report generator: %w", err)
			}

			// Create output directory if it doesn't exist
			if err := os.MkdirAll(outputPath, 0755); err != nil {
				return fmt.Errorf("failed to create output directory: %w", err)
			}

			// Generate quality data
			qualityData, err := CLI.Engine.GenerateReport(context.Background(), CLI.TablePath)
			if err != nil {
				return fmt.Errorf("report generation failed: %w", err)
			}

			// Generate the report
			outputFilePath, err := reportGenerator.GenerateReport(qualityData, "quality", reportFormat, "")
			if err != nil {
				return fmt.Errorf("failed to generate report: %w", err)
			}

			// Print success message
			fmt.Printf("Report successfully generated and saved to: %s\n", outputFilePath)

			return nil
		},
	}

	reportCmd.Flags().StringVar(&CLI.TablePath, "table", "", "Path to Delta Lake table")
	reportCmd.Flags().StringVar(&CLI.OutputFormat, "format", "html", "Report format (html, pdf, json, csv)")
	reportCmd.Flags().StringVar(&CLI.ConfigPath, "output", "./reports", "Directory to save the report")
	reportCmd.Flags().StringVar(&CLI.Token, "template", "", "Path to custom template file")
	CLI.RootCmd.AddCommand(reportCmd)
}

// initUserCmd initializes user management commands
func initUserCmd() {
	userCmd := &cobra.Command{
		Use:   "user",
		Short: "User management",
		Long:  "Manage users and API keys",
	}

	// User management is not implemented yet
	CLI.RootCmd.AddCommand(userCmd)
}

// printSchemaTree recursively prints the schema as an ASCII tree
func printSchemaTree(schema *arrow.Schema, indent int) {
	for i, field := range schema.Fields() {
		for j := 0; j < indent; j++ {
			fmt.Print("  ")
		}
		prefix := "├─"
		if i == len(schema.Fields())-1 {
			prefix = "└─"
		}
		fmt.Printf("%s %s (%s)\n", prefix, field.Name, field.Type)
		// If the field is a struct, recurse (simplified for Arrow)
		if structType, ok := field.Type.(*arrow.StructType); ok {
			subSchema := arrow.NewSchema(structType.Fields(), nil)
			printSchemaTree(subSchema, indent+1)
		}
	}
}

// initSchemaTreeCmd initializes the schema-tree command
func initSchemaTreeCmd() {
	schemaTreeCmd := &cobra.Command{
		Use:   "schema-tree",
		Short: "Display table schema as an ASCII tree",
		Long:  "Prints the schema of a Delta Lake or Parquet table as an ASCII tree.",
		RunE: func(cmd *cobra.Command, args []string) error {
			if CLI.TablePath == "" {
				return fmt.Errorf("table path is required")
			}
			// For simplicity, try to open the file and infer schema
			f, err := os.Open(CLI.TablePath)
			if err != nil {
				return fmt.Errorf("failed to open table: %w", err)
			}
			defer f.Close()
			// Use Arrow IPC to infer schema (could be replaced with actual Parquet schema reading)
			reader, err := ipc.NewReader(f)
			if err != nil {
				return fmt.Errorf("failed to read Arrow IPC: %w", err)
			}
			defer reader.Release()
			schema := reader.Schema()
			fmt.Printf("Schema for table: %s\n", CLI.TablePath)
			printSchemaTree(schema, 0)
			return nil
		},
	}
	schemaTreeCmd.Flags().StringVar(&CLI.TablePath, "table", "", "Path to Delta Lake/Parquet table")
	CLI.RootCmd.AddCommand(schemaTreeCmd)
}

// formatAndPrint formats and prints the result based on output format
func formatAndPrint(result interface{}) error {
	switch CLI.OutputFormat {
	case "json":
		jsonBytes, err := json.MarshalIndent(result, "", "  ")
		if err != nil {
			return fmt.Errorf("failed to format output: %w", err)
		}
		fmt.Println(string(jsonBytes))
	case "yaml":
		// TODO: Implement YAML formatting
	case "text":
		// TODO: Implement text formatting
	default:
		return fmt.Errorf("unsupported output format: %s", CLI.OutputFormat)
	}

	return nil
}
