package cli

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/nessi-dev/nessi/pkg"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/apache/arrow/go/v15/arrow"
	"github.com/apache/arrow/go/v15/arrow/ipc"
	"github.com/nessi-dev/nessi/internal/report"
	"github.com/nessi-dev/nessi/pkg/datalake"
	"github.com/nessi-dev/nessi/pkg/quality/engine"
	"github.com/nessi-dev/nessi/pkg/security"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

// Default HTML template for quality reports
const defaultHTMLTemplate = `<!DOCTYPE html>
<html>
<head>
    <title>Nessi Quality Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            color: #333;
        }
        .header {
            background-color: #2c3e50;
            color: white;
            padding: 20px;
            margin-bottom: 20px;
        }
        .section {
            margin-bottom: 30px;
            border: 1px solid #ddd;
            padding: 15px;
            border-radius: 5px;
        }
        h1, h2, h3 {
            color: #2c3e50;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        .metric-good {
            color: green;
        }
        .metric-warning {
            color: orange;
        }
        .metric-critical {
            color: red;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 0.8em;
            color: #777;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Nessi Quality Report</h1>
        <p>Generated on: {{.timestamp}}</p>
    </div>

    <div class="section">
        <h2>Table Information</h2>
        <p><strong>Table Path:</strong> {{.table_path}}</p>
    </div>

    <div class="section">
        <h2>Data Quality Metrics</h2>
        <table>
            <tr>
                <th>Metric</th>
                <th>Value</th>
                <th>Status</th>
            </tr>
            {{range .data.metrics}}
            <tr>
                <td>{{.name}}</td>
                <td>{{.value}}</td>
                <td class="metric-{{.status}}">{{.status}}</td>
            </tr>
            {{end}}
        </table>
    </div>

    <div class="section">
        <h2>Column Statistics</h2>
        <table>
            <tr>
                <th>Column</th>
                <th>Type</th>
                <th>Min</th>
                <th>Max</th>
                <th>Avg</th>
                <th>Null %</th>
            </tr>
            {{range .data.columns}}
            <tr>
                <td>{{.name}}</td>
                <td>{{.type}}</td>
                <td>{{.min}}</td>
                <td>{{.max}}</td>
                <td>{{.avg}}</td>
                <td>{{.null_percent}}%</td>
            </tr>
            {{end}}
        </table>
    </div>

    <div class="footer">
        <p>Generated by Nessi CLI v0.10.3 | © 2023-2025 Nessi Project</p>
    </div>
</body>
</html>`

// CLI represents the command-line interface
var CLI struct {
	RootCmd      *cobra.Command
	Config       *viper.Viper
	Engine       engine.QualityEngine
	Security     *security.SecurityManager
	Datalake     *datalake.Reader
	ConfigPath   string
	Token        string
	TablePath    string
	OutputFormat string
}

// Init initializes the CLI
func Init() {
	// Add info command
	infoCmd := &cobra.Command{
		Use:   "info",
		Short: "Show Nessi CLI and feature info",
		Long:  "Display information about the Nessi CLI, enabled features, and upgrade options.",
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Printf(`\nNessi CLI %s\n`, CLI.RootCmd.Version)
			fmt.Println("Delta Lake support: enabled")
			fmt.Println("Python extensions: enabled")
			fmt.Println("Telemetry: disabled")
			fmt.Println("Team features: not available (OSS Edition)")
			fmt.Println("\n→ Want RCA dashboards, team alerts, or governance features?")
			fmt.Print("   Learn about LakeDiff: https://lakediff.com\n")
			os.Exit(0)
		},
	}
	CLI.RootCmd.AddCommand(infoCmd)

	CLI.Config = viper.New()
	CLI.RootCmd = &cobra.Command{
		Use:   "nessi",
		Short: "Nessi - Delta Lake Data Quality Tool",
		Long: `Nessi is a powerful tool for managing data quality in Delta Lake tables.
It provides features for validation, profiling, monitoring, and reporting.`,
		Version: "v0.10.3", // Update as needed
	} // Add Version field to the root command

	// Add global flags
	CLI.RootCmd.PersistentFlags().StringVar(&CLI.ConfigPath, "config", "", "Path to configuration file")
	CLI.RootCmd.PersistentFlags().StringVar(&CLI.Token, "token", "", "Authentication token")
	CLI.RootCmd.PersistentFlags().StringVar(&CLI.OutputFormat, "output", "json", "Output format (json|yaml|text)")

	// Initialize subcommands
	initValidateCmd()
	initProfileCmd()
	initMonitorCmd()
	initReportCmd()
	initUserCmd()
	initSchemaTreeCmd() // Register the new schema-tree command
	// RCA command is disabled due to missing implementation
	CLI.RootCmd.AddCommand(telemetryCmd)
}

// Execute runs the CLI
func Execute() error {
	cfg := pkg.GetTelemetryConfig()
	telemetryManager := pkg.NewTelemetryManager(cfg)
	CLI.RootCmd.PersistentPreRun = func(cmd *cobra.Command, args []string) {
		// Send telemetry event for every command
		telemetryManager.SendEvent(pkg.TelemetryEvent{
			Timestamp: time.Now(),
			Command:   cmd.Name(),
			Args:      args,
			Success:   true, // Set to false on error in future
			Error:     "",
			Version:   "v0.1.0", // TODO: set dynamically
		})
	}
	return CLI.RootCmd.Execute()
}

func init() {
	// Initialize RootCmd if it's nil
	if CLI.RootCmd == nil {
		CLI.RootCmd = &cobra.Command{
			Use:   "nessi",
			Short: "Nessi - Delta Lake Data Quality Tool",
			Long:  "Nessi is a data quality tool for Delta Lake tables",
		}
	}

	// Now it's safe to add commands
	CLI.RootCmd.AddCommand(telemetryCmd)

	CLI.RootCmd.Version = "v0.10.3"
	CLI.RootCmd.SetVersionTemplate(`Nessi CLI {{.Version}} — OSS edition\nLooking for team features like Slack alerts and dashboards? See LakeDiff → https://lakediff.com\n`)
}

// initValidateCmd initializes the validate command
func initValidateCmd() {
	validateCmd := &cobra.Command{
		Use:   "validate",
		Short: "Validate data quality rules",
		Long:  "Validate data quality rules for a Delta Lake table",
		RunE: func(cmd *cobra.Command, args []string) error {
			if CLI.TablePath == "" {
				return fmt.Errorf("table path is required")
			}

			// Initialize engine and datalake reader
			engine := engine.New()
			datalake, err := datalake.NewReader(CLI.TablePath)
			if err != nil {
				return fmt.Errorf("failed to create datalake reader: %w", err)
			}
			if err := datalake.Initialize(); err != nil {
				return fmt.Errorf("failed to initialize datalake reader: %w", err)
			}

			// Validate table
			result, err := engine.ValidateTable(context.Background(), CLI.TablePath)
			if err != nil {
				return fmt.Errorf("validation failed: %w", err)
			}

			// Format and print result
			return formatAndPrint(result)
		},
	}

	validateCmd.Flags().StringVar(&CLI.TablePath, "table", "", "Path to Delta Lake table")
	CLI.RootCmd.AddCommand(validateCmd)
}

// initProfileCmd initializes the profile command
func initProfileCmd() {
	profileCmd := &cobra.Command{
		Use:   "profile",
		Short: "Generate data profile",
		Long:  "Generate a data profile for a Delta Lake table",
		RunE: func(cmd *cobra.Command, args []string) error {
			if CLI.TablePath == "" {
				return fmt.Errorf("table path is required")
			}

			// Initialize engine and datalake reader
			engine := engine.New()
			datalake, err := datalake.NewReader(CLI.TablePath)
			if err != nil {
				return fmt.Errorf("failed to create datalake reader: %w", err)
			}
			if err := datalake.Initialize(); err != nil {
				return fmt.Errorf("failed to initialize datalake reader: %w", err)
			}

			// Profile table
			result, err := engine.ProfileTable(context.Background(), CLI.TablePath)
			if err != nil {
				return fmt.Errorf("profiling failed: %w", err)
			}

			// Format and print result
			return formatAndPrint(result)
		},
	}

	profileCmd.Flags().StringVar(&CLI.TablePath, "table", "", "Path to Delta Lake table")
	CLI.RootCmd.AddCommand(profileCmd)
}

// initMonitorCmd initializes the monitor command
func initMonitorCmd() {
	monitorCmd := &cobra.Command{
		Use:   "monitor",
		Short: "Monitor table metrics",
		Long:  "Monitor metrics for a Delta Lake table", // OSS: removed alert mention
		RunE: func(cmd *cobra.Command, args []string) error {
			if CLI.TablePath == "" {
				return fmt.Errorf("table path is required")
			}

			// Initialize engine and datalake reader
			engine := engine.New()
			datalake, err := datalake.NewReader(CLI.TablePath)
			if err != nil {
				return fmt.Errorf("failed to create datalake reader: %w", err)
			}
			if err := datalake.Initialize(); err != nil {
				return fmt.Errorf("failed to initialize datalake reader: %w", err)
			}

			// Monitor table
			result, err := engine.MonitorTable(context.Background(), CLI.TablePath)
			if err != nil {
				return fmt.Errorf("monitoring failed: %w", err)
			}

			// Format and print result
			return formatAndPrint(result)
		},
	}

	monitorCmd.Flags().StringVar(&CLI.TablePath, "table", "", "Path to Delta Lake table")
	CLI.RootCmd.AddCommand(monitorCmd)
}

// initReportCmd initializes the report command
func initReportCmd() {
	// Define report format and output path variables
	var reportFormat string
	var outputPath string
	var templatePath string

	reportCmd := &cobra.Command{
		Use:   "report",
		Short: "Generate quality report",
		Long:  "Generate a comprehensive quality report for a Delta Lake table",
		RunE: func(cmd *cobra.Command, args []string) error {
			if CLI.TablePath == "" {
				return fmt.Errorf("table path is required")
			}

			// Initialize engine and datalake reader
			engine := engine.New()
			datalake, err := datalake.NewReader(CLI.TablePath)
			if err != nil {
				return fmt.Errorf("failed to create datalake reader: %w", err)
			}
			if err := datalake.Initialize(); err != nil {
				return fmt.Errorf("failed to initialize datalake reader: %w", err)
			}

			// Create report manager
			reportManager, err := report.NewManager(outputPath)
			if err != nil {
				return fmt.Errorf("failed to create report manager: %w", err)
			}

			// Load template if specified
			if templatePath != "" {
				templateContent, err := os.ReadFile(templatePath)
				if err != nil {
					return fmt.Errorf("failed to read template file: %w", err)
				}

				// Determine template format based on file extension
				templateFormat := report.HTML
				switch {
				case strings.HasSuffix(templatePath, ".html"):
					templateFormat = report.HTML
				case strings.HasSuffix(templatePath, ".json"):
					templateFormat = report.JSON
				case strings.HasSuffix(templatePath, ".csv"):
					templateFormat = report.CSV
				}

				// Register template
				template := report.ReportTemplate{
					ID:          "quality_report",
					Name:        "Quality Report",
					Description: "A comprehensive quality report for Delta Lake tables",
					Format:      templateFormat,
					Template:    string(templateContent),
					Parameters:  []string{"table_path", "timestamp"},
				}

				if err := reportManager.AddTemplate(template); err != nil {
					return fmt.Errorf("failed to add template: %w", err)
				}
			} else {
				// Register default templates based on format
				var templateContent string
				var templateFormat report.ReportFormat

				switch reportFormat {
				case "html":
					templateContent = defaultHTMLTemplate
					templateFormat = report.HTML
				case "json":
					templateContent = "{}" // Empty JSON template
					templateFormat = report.JSON
				case "csv":
					templateContent = "" // Empty CSV template
					templateFormat = report.CSV
				case "pdf":
					templateContent = defaultHTMLTemplate // Use HTML for PDF generation
					templateFormat = report.PDF
				default:
					return fmt.Errorf("unsupported report format: %s", reportFormat)
				}

				// Register template
				template := report.ReportTemplate{
					ID:          "quality_report",
					Name:        "Quality Report",
					Description: "A comprehensive quality report for Delta Lake tables",
					Format:      templateFormat,
					Template:    templateContent,
					Parameters:  []string{"table_path", "timestamp"},
				}

				if err := reportManager.AddTemplate(template); err != nil {
					return fmt.Errorf("failed to add template: %w", err)
				}
			}

			// Generate quality data
			qualityData, err := engine.GenerateReport(context.Background(), CLI.TablePath)
			if err != nil {
				return fmt.Errorf("report generation failed: %w", err)
			}

			// Set up report parameters
			params := map[string]interface{}{
				"table_path": CLI.TablePath,
				"timestamp":  time.Now().Format(time.RFC3339),
				"data":       qualityData,
			}

			// Generate report
			reportObj, err := reportManager.GenerateReport(context.Background(), "quality_report", params)
			if err != nil {
				return fmt.Errorf("failed to generate report: %w", err)
			}

			// Save report
			if err := reportManager.SaveReport(reportObj); err != nil {
				return fmt.Errorf("failed to save report: %w", err)
			}

			// Print success message
			filePath := filepath.Join(outputPath, fmt.Sprintf("%s.%s", reportObj.ID, reportObj.Format))
			fmt.Printf("Report successfully generated and saved to: %s\n", filePath)

			return nil
		},
	}

	reportCmd.Flags().StringVar(&CLI.TablePath, "table", "", "Path to Delta Lake table")
	reportCmd.Flags().StringVar(&reportFormat, "format", "html", "Report format (html, pdf, json, csv)")
	reportCmd.Flags().StringVar(&outputPath, "output", "./reports", "Directory to save the report")
	reportCmd.Flags().StringVar(&templatePath, "template", "", "Path to custom template file")
	CLI.RootCmd.AddCommand(reportCmd)
}

// initUserCmd initializes user management commands
func initUserCmd() {
	userCmd := &cobra.Command{
		Use:   "user",
		Short: "User management",
		Long:  "Manage users and API keys",
	}

	// User management is not implemented yet
	CLI.RootCmd.AddCommand(userCmd)
}

// printSchemaTree recursively prints the schema as an ASCII tree
func printSchemaTree(schema *arrow.Schema, indent int) {
	for i, field := range schema.Fields() {
		for j := 0; j < indent; j++ {
			fmt.Print("  ")
		}
		prefix := "├─"
		if i == len(schema.Fields())-1 {
			prefix = "└─"
		}
		fmt.Printf("%s %s (%s)\n", prefix, field.Name, field.Type)
		// If the field is a struct, recurse (simplified for Arrow)
		if structType, ok := field.Type.(*arrow.StructType); ok {
			subSchema := arrow.NewSchema(structType.Fields(), nil)
			printSchemaTree(subSchema, indent+1)
		}
	}
}

// initSchemaTreeCmd initializes the schema-tree command
func initSchemaTreeCmd() {
	schemaTreeCmd := &cobra.Command{
		Use:   "schema-tree",
		Short: "Display table schema as an ASCII tree",
		Long:  "Prints the schema of a Delta Lake or Parquet table as an ASCII tree.",
		RunE: func(cmd *cobra.Command, args []string) error {
			if CLI.TablePath == "" {
				return fmt.Errorf("table path is required")
			}
			// For simplicity, try to open the file and infer schema
			f, err := os.Open(CLI.TablePath)
			if err != nil {
				return fmt.Errorf("failed to open table: %w", err)
			}
			defer f.Close()
			// Use Arrow IPC to infer schema (could be replaced with actual Parquet schema reading)
			reader, err := ipc.NewReader(f)
			if err != nil {
				return fmt.Errorf("failed to read Arrow IPC: %w", err)
			}
			defer reader.Release()
			schema := reader.Schema()
			fmt.Printf("Schema for table: %s\n", CLI.TablePath)
			printSchemaTree(schema, 0)
			return nil
		},
	}
	schemaTreeCmd.Flags().StringVar(&CLI.TablePath, "table", "", "Path to Delta Lake/Parquet table")
	CLI.RootCmd.AddCommand(schemaTreeCmd)
}

// formatAndPrint formats and prints the result based on output format
func formatAndPrint(result interface{}) error {
	switch CLI.OutputFormat {
	case "json":
		jsonBytes, err := json.MarshalIndent(result, "", "  ")
		if err != nil {
			return fmt.Errorf("failed to format output: %w", err)
		}
		fmt.Println(string(jsonBytes))
	case "yaml":
		// TODO: Implement YAML formatting
	case "text":
		// TODO: Implement text formatting
	default:
		return fmt.Errorf("unsupported output format: %s", CLI.OutputFormat)
	}

	return nil
}
