// Implementation of monitoring and alerting features.

package alerts

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sync"
	"time"
)

// AlertSeverity represents the severity level of an alert
type AlertSeverity string

const (
	// SeverityInfo represents an informational alert
	SeverityInfo AlertSeverity = "info"

	// SeverityWarning represents a warning alert
	SeverityWarning AlertSeverity = "warning"

	// SeverityCritical represents a critical alert
	SeverityCritical AlertSeverity = "critical"
)

// AlertStatus represents the status of an alert
type AlertStatus string

const (
	// StatusActive represents an active alert
	StatusActive AlertStatus = "active"

	// StatusAcknowledged represents an acknowledged alert
	StatusAcknowledged AlertStatus = "acknowledged"

	// StatusResolved represents a resolved alert
	StatusResolved AlertStatus = "resolved"

	// StatusSilenced represents a silenced alert
	StatusSilenced AlertStatus = "silenced"
)

// AlertType represents the type of alert
type AlertType string

const (
	// TypeQuality represents a data quality alert
	TypeQuality AlertType = "quality"

	// TypeAnomaly represents an anomaly detection alert
	TypeAnomaly AlertType = "anomaly"

	// TypeSystem represents a system alert
	TypeSystem AlertType = "system"

	// TypeCustom represents a custom alert
	TypeCustom AlertType = "custom"
)

// AlertNotification represents a notification for an alert
type AlertNotification struct {
	// ID is the unique identifier for the notification
	ID string `json:"id"`

	// AlertID is the ID of the alert
	AlertID string `json:"alert_id"`

	// Channel is the notification channel (email, webhook)
	Channel string `json:"channel"`

	// Recipient is the recipient of the notification
	Recipient string `json:"recipient"`

	// SentAt is the time the notification was sent
	SentAt time.Time `json:"sent_at"`

	// Status is the status of the notification (sent, delivered, failed)
	Status string `json:"status"`

	// ErrorMessage is the error message if the notification failed
	ErrorMessage string `json:"error_message,omitempty"`
}

// Alert represents an alert
type Alert struct {
	// ID is the unique identifier for the alert
	ID string `json:"id"`

	// Name is the name of the alert
	Name string `json:"name"`

	// Description is the description of the alert
	Description string `json:"description"`

	// Type is the type of alert
	Type AlertType `json:"type"`

	// Severity is the severity of the alert
	Severity AlertSeverity `json:"severity"`

	// Status is the status of the alert
	Status AlertStatus `json:"status"`

	// Source is the source of the alert (table name, metric name, etc.)
	Source string `json:"source"`

	// Timestamp is the time the alert was created
	Timestamp time.Time `json:"timestamp"`

	// LastUpdated is the time the alert was last updated
	LastUpdated time.Time `json:"last_updated"`

	// ResolvedAt is the time the alert was resolved
	ResolvedAt *time.Time `json:"resolved_at,omitempty"`

	// AcknowledgedAt is the time the alert was acknowledged
	AcknowledgedAt *time.Time `json:"acknowledged_at,omitempty"`

	// AcknowledgedBy is the user who acknowledged the alert
	AcknowledgedBy string `json:"acknowledged_by,omitempty"`

	// SilencedUntil is the time until which the alert is silenced
	SilencedUntil *time.Time `json:"silenced_until,omitempty"`

	// SilencedBy is the user who silenced the alert
	SilencedBy string `json:"silenced_by,omitempty"`

	// SilenceReason is the reason for silencing the alert
	SilenceReason string `json:"silence_reason,omitempty"`

	// Labels are key-value pairs for the alert
	Labels map[string]string `json:"labels,omitempty"`

	// Annotations are additional information for the alert
	Annotations map[string]string `json:"annotations,omitempty"`

	// Value is the value that triggered the alert
	Value float64 `json:"value,omitempty"`

	// Threshold is the threshold that was exceeded
	Threshold float64 `json:"threshold,omitempty"`

	// ComparisonOperator is the comparison operator used (>, <, ==, etc.)
	ComparisonOperator string `json:"comparison_operator,omitempty"`

	// Notifications are the notifications sent for this alert
	Notifications []*AlertNotification `json:"notifications,omitempty"`
}

// AlertRule represents a rule for generating alerts
type AlertRule struct {
	// ID is the unique identifier for the rule
	ID string `json:"id"`

	// Name is the name of the rule
	Name string `json:"name"`

	// Description is the description of the rule
	Description string `json:"description"`

	// Type is the type of alert this rule generates
	Type AlertType `json:"type"`

	// Severity is the severity of alerts generated by this rule
	Severity AlertSeverity `json:"severity"`

	// Source is the source to monitor (table name, metric name, etc.)
	Source string `json:"source"`

	// Metric is the metric to monitor
	Metric string `json:"metric"`

	// Threshold is the threshold for triggering an alert
	Threshold float64 `json:"threshold"`

	// ComparisonOperator is the comparison operator to use (>, <, ==, etc.)
	ComparisonOperator string `json:"comparison_operator"`

	// WindowSize is the time window to consider for the metric
	WindowSize time.Duration `json:"window_size"`

	// EvaluationInterval is how often to evaluate the rule
	EvaluationInterval time.Duration `json:"evaluation_interval"`

	// Labels are key-value pairs for alerts generated by this rule
	Labels map[string]string `json:"labels,omitempty"`

	// Annotations are additional information for alerts generated by this rule
	Annotations map[string]string `json:"annotations,omitempty"`

	// NotificationChannels are the channels to notify when an alert is triggered
	NotificationChannels []string `json:"notification_channels,omitempty"`

	// Recipients are the recipients to notify when an alert is triggered
	Recipients []string `json:"recipients,omitempty"`

	// Enabled indicates whether the rule is enabled
	Enabled bool `json:"enabled"`

	// CreatedAt is the time the rule was created
	CreatedAt time.Time `json:"created_at"`

	// UpdatedAt is the time the rule was last updated
	UpdatedAt time.Time `json:"updated_at"`

	// LastTriggered is the time the rule last triggered an alert
	LastTriggered time.Time `json:"last_triggered,omitempty"`

	// CreatedBy is the user who created the rule
	CreatedBy string `json:"created_by"`

	// UpdatedBy is the user who last updated the rule
	UpdatedBy string `json:"updated_by,omitempty"`
}

// AlertManager manages alerts and alert rules
type AlertManager struct {
	// dataDir is the directory where alert data is stored
	dataDir string

	// alerts is a map of alert ID to alert
	alerts map[string]*Alert

	// rules is a map of rule ID to rule
	rules map[string]*AlertRule

	// notifiers is a map of notification channel to notifier
	notifiers map[string]Notifier

	// mu is a mutex for thread safety
	mu sync.RWMutex
}

// Notifier is an interface for sending notifications
type Notifier interface {
	// Send sends a notification
	Send(alert *Alert, recipient string) (*AlertNotification, error)

	// Name returns the name of the notifier
	Name() string
}

// NewAlertManager creates a new alert manager
func NewAlertManager(dataDir string) (*AlertManager, error) {
	// Create data directory if it doesn't exist
	if err := os.MkdirAll(dataDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create data directory: %w", err)
	}

	// Create alerts directory if it doesn't exist
	alertsDir := filepath.Join(dataDir, "alerts")
	if err := os.MkdirAll(alertsDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create alerts directory: %w", err)
	}

	// Create rules directory if it doesn't exist
	rulesDir := filepath.Join(dataDir, "rules")
	if err := os.MkdirAll(rulesDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create rules directory: %w", err)
	}

	// Create notifications directory if it doesn't exist
	notificationsDir := filepath.Join(dataDir, "notifications")
	if err := os.MkdirAll(notificationsDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create notifications directory: %w", err)
	}

	manager := &AlertManager{
		dataDir:   dataDir,
		alerts:    make(map[string]*Alert),
		rules:     make(map[string]*AlertRule),
		notifiers: make(map[string]Notifier),
	}

	// Load existing alerts and rules
	if err := manager.loadAlerts(); err != nil {
		return nil, fmt.Errorf("failed to load alerts: %w", err)
	}

	if err := manager.loadRules(); err != nil {
		return nil, fmt.Errorf("failed to load rules: %w", err)
	}

	return manager, nil
}

// RegisterNotifier registers a notifier
func (am *AlertManager) RegisterNotifier(notifier Notifier) {
	am.mu.Lock()
	defer am.mu.Unlock()

	am.notifiers[notifier.Name()] = notifier
}

// CreateAlert creates a new alert
func (am *AlertManager) CreateAlert(alert *Alert) error {
	am.mu.Lock()
	defer am.mu.Unlock()

	// Validate alert
	if alert.ID == "" {
		return fmt.Errorf("alert ID is required")
	}

	if alert.Name == "" {
		return fmt.Errorf("alert name is required")
	}

	if alert.Source == "" {
		return fmt.Errorf("alert source is required")
	}

	// Set timestamps if not set
	if alert.Timestamp.IsZero() {
		alert.Timestamp = time.Now()
	}

	if alert.LastUpdated.IsZero() {
		alert.LastUpdated = alert.Timestamp
	}

	// Set default status if not set
	if alert.Status == "" {
		alert.Status = StatusActive
	}

	// Save alert
	am.alerts[alert.ID] = alert

	// Write alert to disk
	if err := am.saveAlert(alert); err != nil {
		delete(am.alerts, alert.ID)
		return fmt.Errorf("failed to save alert: %w", err)
	}

	return nil
}

// GetAlert gets an alert by ID
func (am *AlertManager) GetAlert(id string) (*Alert, error) {
	am.mu.RLock()
	defer am.mu.RUnlock()

	alert, ok := am.alerts[id]
	if !ok {
		return nil, fmt.Errorf("alert not found: %s", id)
	}

	return alert, nil
}

// UpdateAlert updates an alert
func (am *AlertManager) UpdateAlert(alert *Alert) error {
	am.mu.Lock()
	defer am.mu.Unlock()

	// Check if alert exists
	_, ok := am.alerts[alert.ID]
	if !ok {
		return fmt.Errorf("alert not found: %s", alert.ID)
	}

	// Update last updated timestamp
	alert.LastUpdated = time.Now()

	// Save alert
	am.alerts[alert.ID] = alert

	// Write alert to disk
	if err := am.saveAlert(alert); err != nil {
		return fmt.Errorf("failed to save alert: %w", err)
	}

	return nil
}

// DeleteAlert deletes an alert
func (am *AlertManager) DeleteAlert(id string) error {
	am.mu.Lock()
	defer am.mu.Unlock()

	// Check if alert exists
	_, ok := am.alerts[id]
	if !ok {
		return fmt.Errorf("alert not found: %s", id)
	}

	// Delete alert from memory
	delete(am.alerts, id)

	// Delete alert file
	alertPath := filepath.Join(am.dataDir, "alerts", id+".json")
	if err := os.Remove(alertPath); err != nil {
		return fmt.Errorf("failed to delete alert file: %w", err)
	}

	return nil
}

// GetAlerts gets all alerts
func (am *AlertManager) GetAlerts() []*Alert {
	am.mu.RLock()
	defer am.mu.RUnlock()

	alerts := make([]*Alert, 0, len(am.alerts))
	for _, alert := range am.alerts {
		alerts = append(alerts, alert)
	}

	return alerts
}

// GetAlertsByStatus gets alerts by status
func (am *AlertManager) GetAlertsByStatus(status AlertStatus) []*Alert {
	am.mu.RLock()
	defer am.mu.RUnlock()

	alerts := make([]*Alert, 0)
	for _, alert := range am.alerts {
		if alert.Status == status {
			alerts = append(alerts, alert)
		}
	}

	return alerts
}

// GetAlertsByType gets alerts by type
func (am *AlertManager) GetAlertsByType(alertType AlertType) []*Alert {
	am.mu.RLock()
	defer am.mu.RUnlock()

	alerts := make([]*Alert, 0)
	for _, alert := range am.alerts {
		if alert.Type == alertType {
			alerts = append(alerts, alert)
		}
	}

	return alerts
}

// GetAlertsBySeverity gets alerts by severity
func (am *AlertManager) GetAlertsBySeverity(severity AlertSeverity) []*Alert {
	am.mu.RLock()
	defer am.mu.RUnlock()

	alerts := make([]*Alert, 0)
	for _, alert := range am.alerts {
		if alert.Severity == severity {
			alerts = append(alerts, alert)
		}
	}

	return alerts
}

// AcknowledgeAlert acknowledges an alert
func (am *AlertManager) AcknowledgeAlert(id, acknowledgedBy string) error {
	am.mu.Lock()
	defer am.mu.Unlock()

	// Check if alert exists
	alert, ok := am.alerts[id]
	if !ok {
		return fmt.Errorf("alert not found: %s", id)
	}

	// Update alert status
	alert.Status = StatusAcknowledged
	alert.LastUpdated = time.Now()
	now := time.Now()
	alert.AcknowledgedAt = &now
	alert.AcknowledgedBy = acknowledgedBy

	// Write alert to disk
	if err := am.saveAlert(alert); err != nil {
		return fmt.Errorf("failed to save alert: %w", err)
	}

	return nil
}

// ResolveAlert resolves an alert
func (am *AlertManager) ResolveAlert(id string) error {
	am.mu.Lock()
	defer am.mu.Unlock()

	// Check if alert exists
	alert, ok := am.alerts[id]
	if !ok {
		return fmt.Errorf("alert not found: %s", id)
	}

	// Update alert status
	alert.Status = StatusResolved
	alert.LastUpdated = time.Now()
	now := time.Now()
	alert.ResolvedAt = &now

	// Write alert to disk
	if err := am.saveAlert(alert); err != nil {
		return fmt.Errorf("failed to save alert: %w", err)
	}

	return nil
}

// SilenceAlert silences an alert
func (am *AlertManager) SilenceAlert(id, silencedBy, reason string, duration time.Duration) error {
	am.mu.Lock()
	defer am.mu.Unlock()

	// Check if alert exists
	alert, ok := am.alerts[id]
	if !ok {
		return fmt.Errorf("alert not found: %s", id)
	}

	// Update alert status
	alert.Status = StatusSilenced
	alert.LastUpdated = time.Now()
	silencedUntil := time.Now().Add(duration)
	alert.SilencedUntil = &silencedUntil
	alert.SilencedBy = silencedBy
	alert.SilenceReason = reason

	// Write alert to disk
	if err := am.saveAlert(alert); err != nil {
		return fmt.Errorf("failed to save alert: %w", err)
	}

	return nil
}

// CreateRule creates a new alert rule
func (am *AlertManager) CreateRule(rule *AlertRule) error {
	am.mu.Lock()
	defer am.mu.Unlock()

	// Validate rule
	if rule.ID == "" {
		return fmt.Errorf("rule ID is required")
	}

	if rule.Name == "" {
		return fmt.Errorf("rule name is required")
	}

	if rule.Source == "" {
		return fmt.Errorf("rule source is required")
	}

	if rule.Metric == "" {
		return fmt.Errorf("rule metric is required")
	}

	// Check if rule with same ID already exists
	if _, ok := am.rules[rule.ID]; ok {
		return fmt.Errorf("rule already exists: %s", rule.ID)
	}

	// Set created time if not set
	if rule.CreatedAt.IsZero() {
		rule.CreatedAt = time.Now()
	}

	// Set updated time if not set
	if rule.UpdatedAt.IsZero() {
		rule.UpdatedAt = rule.CreatedAt
	}

	// Add rule to memory
	am.rules[rule.ID] = rule

	// Write rule to disk
	if err := am.saveRule(rule); err != nil {
		// Remove rule from memory on error
		delete(am.rules, rule.ID)
		return fmt.Errorf("failed to save rule: %w", err)
	}

	return nil
}

// GetRule gets a rule by ID
func (am *AlertManager) GetRule(id string) (*AlertRule, error) {
	am.mu.RLock()
	defer am.mu.RUnlock()

	rule, ok := am.rules[id]
	if !ok {
		return nil, fmt.Errorf("rule not found: %s", id)
	}

	return rule, nil
}

// UpdateRule updates a rule
func (am *AlertManager) UpdateRule(rule *AlertRule) error {
	am.mu.Lock()
	defer am.mu.Unlock()

	// Check if rule exists
	existingRule, ok := am.rules[rule.ID]
	if !ok {
		return fmt.Errorf("rule not found: %s", rule.ID)
	}

	// Update rule
	rule.UpdatedAt = time.Now()
	am.rules[rule.ID] = rule

	// Write rule to disk
	if err := am.saveRule(rule); err != nil {
		// Restore previous rule on error
		am.rules[rule.ID] = existingRule
		return fmt.Errorf("failed to save rule: %w", err)
	}

	return nil
}

// DeleteRule deletes a rule
func (am *AlertManager) DeleteRule(id string) error {
	am.mu.Lock()
	defer am.mu.Unlock()

	// Check if rule exists
	_, ok := am.rules[id]
	if !ok {
		return fmt.Errorf("rule not found: %s", id)
	}

	// Delete rule from memory
	delete(am.rules, id)

	// Delete rule file
	rulePath := filepath.Join(am.dataDir, "rules", id+".json")
	if err := os.Remove(rulePath); err != nil {
		return fmt.Errorf("failed to delete rule file: %w", err)
	}

	return nil
}

// GetRules gets all rules
func (am *AlertManager) GetRules() []*AlertRule {
	am.mu.RLock()
	defer am.mu.RUnlock()

	rules := make([]*AlertRule, 0, len(am.rules))
	for _, rule := range am.rules {
		rules = append(rules, rule)
	}

	return rules
}

// GetRulesByType gets rules by type
func (am *AlertManager) GetRulesByType(ruleType AlertType) []*AlertRule {
	am.mu.RLock()
	defer am.mu.RUnlock()

	rules := make([]*AlertRule, 0)
	for _, rule := range am.rules {
		if rule.Type == ruleType {
			rules = append(rules, rule)
		}
	}

	return rules
}

// GetEnabledRules gets all enabled rules
func (am *AlertManager) GetEnabledRules() []*AlertRule {
	am.mu.RLock()
	defer am.mu.RUnlock()

	rules := make([]*AlertRule, 0)
	for _, rule := range am.rules {
		if rule.Enabled {
			rules = append(rules, rule)
		}
	}

	return rules
}

// AddNotification adds a notification to an alert
func (am *AlertManager) AddNotification(alertID string, notification *AlertNotification) error {
	am.mu.Lock()
	defer am.mu.Unlock()

	// Check if alert exists
	alert, ok := am.alerts[alertID]
	if !ok {
		return fmt.Errorf("alert not found: %s", alertID)
	}

	// Add notification
	alert.Notifications = append(alert.Notifications, notification)

	// Write alert to disk
	if err := am.saveAlert(alert); err != nil {
		return fmt.Errorf("failed to save alert: %w", err)
	}

	return nil
}

// SendNotification sends a notification for an alert
func (am *AlertManager) SendNotification(alertID, channel, recipient string) (*AlertNotification, error) {
	am.mu.Lock()
	defer am.mu.Unlock()

	// Check if alert exists
	alert, ok := am.alerts[alertID]
	if !ok {
		return nil, fmt.Errorf("alert not found: %s", alertID)
	}

	// Check if notifier exists
	notifier, ok := am.notifiers[channel]
	if !ok {
		return nil, fmt.Errorf("notifier not found: %s", channel)
	}

	// Send notification
	notification, err := notifier.Send(alert, recipient)
	if err != nil {
		return nil, fmt.Errorf("failed to send notification: %w", err)
	}

	// Add notification to alert
	alert.Notifications = append(alert.Notifications, notification)

	// Write alert to disk
	if err := am.saveAlert(alert); err != nil {
		return nil, fmt.Errorf("failed to save alert: %w", err)
	}

	return notification, nil
}

// loadAlerts loads alerts from disk
func (am *AlertManager) loadAlerts() error {
	alertsDir := filepath.Join(am.dataDir, "alerts")

	// Read alert files
	files, err := os.ReadDir(alertsDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("failed to read alerts directory: %w", err)
	}

	// Load each alert
	for _, file := range files {
		if file.IsDir() || filepath.Ext(file.Name()) != ".json" {
			continue
		}

		// Read alert file
		alertPath := filepath.Join(alertsDir, file.Name())
		alertData, err := os.ReadFile(alertPath)
		if err != nil {
			return fmt.Errorf("failed to read alert file: %w", err)
		}

		// Unmarshal alert
		var alert Alert
		if err := json.Unmarshal(alertData, &alert); err != nil {
			return fmt.Errorf("failed to unmarshal alert: %w", err)
		}

		// Add alert to memory
		am.alerts[alert.ID] = &alert
	}

	return nil
}

// loadRules loads rules from disk
func (am *AlertManager) loadRules() error {
	rulesDir := filepath.Join(am.dataDir, "rules")

	// Read rule files
	files, err := os.ReadDir(rulesDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("failed to read rules directory: %w", err)
	}

	// Load each rule
	for _, file := range files {
		if file.IsDir() || filepath.Ext(file.Name()) != ".json" {
			continue
		}

		// Read rule file
		rulePath := filepath.Join(rulesDir, file.Name())
		ruleData, err := os.ReadFile(rulePath)
		if err != nil {
			return fmt.Errorf("failed to read rule file: %w", err)
		}

		// Unmarshal rule
		var rule AlertRule
		if err := json.Unmarshal(ruleData, &rule); err != nil {
			return fmt.Errorf("failed to unmarshal rule: %w", err)
		}

		// Add rule to memory
		am.rules[rule.ID] = &rule
	}

	return nil
}

// saveAlert saves an alert to disk
func (am *AlertManager) saveAlert(alert *Alert) error {
	// Marshal alert
	alertData, err := json.MarshalIndent(alert, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal alert: %w", err)
	}

	// Write alert file
	alertPath := filepath.Join(am.dataDir, "alerts", alert.ID+".json")
	if err := os.WriteFile(alertPath, alertData, 0644); err != nil {
		return fmt.Errorf("failed to write alert file: %w", err)
	}

	return nil
}

// saveRule saves a rule to disk
func (am *AlertManager) saveRule(rule *AlertRule) error {
	// Marshal rule
	ruleData, err := json.MarshalIndent(rule, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal rule: %w", err)
	}

	// Write rule file
	rulePath := filepath.Join(am.dataDir, "rules", rule.ID+".json")
	if err := os.WriteFile(rulePath, ruleData, 0644); err != nil {
		return fmt.Errorf("failed to write rule file: %w", err)
	}

	return nil
}
